
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductWebService", targetNamespace = "http://soapwebservice.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductWebService {


    /**
     * 
     * @param id
     * @return
     *     returns proxy.Product
     */
    @WebMethod
    @WebResult(name = "product", targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetProductResponse")
    @Action(input = "http://soapwebservice.example.com/ProductWebService/getProductRequest", output = "http://soapwebservice.example.com/ProductWebService/getProductResponse")
    public Product getProduct(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "fillTheDB", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.FillTheDB")
    @ResponseWrapper(localName = "fillTheDBResponse", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.FillTheDBResponse")
    @Action(input = "http://soapwebservice.example.com/ProductWebService/fillTheDBRequest", output = "http://soapwebservice.example.com/ProductWebService/fillTheDBResponse")
    public void fillTheDB();

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Product>
     */
    @WebMethod
    @WebResult(name = "products", targetNamespace = "")
    @RequestWrapper(localName = "getProductList", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetProductListResponse")
    @Action(input = "http://soapwebservice.example.com/ProductWebService/getProductListRequest", output = "http://soapwebservice.example.com/ProductWebService/getProductListResponse")
    public List<Product> getProductList();

    /**
     * 
     * @param price
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(name = "sellingPrice", targetNamespace = "")
    @RequestWrapper(localName = "getSellingPrice", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetSellingPrice")
    @ResponseWrapper(localName = "getSellingPriceResponse", targetNamespace = "http://soapwebservice.example.com/", className = "proxy.GetSellingPriceResponse")
    @Action(input = "http://soapwebservice.example.com/ProductWebService/getSellingPriceRequest", output = "http://soapwebservice.example.com/ProductWebService/getSellingPriceResponse")
    public Double getSellingPrice(
        @WebParam(name = "price", targetNamespace = "")
        Double price);

}
